### ISSUE TITLE
forse è solo un piccolo bug mio...

### ISSUE THREAD

**Issue by Pollo2** [MrAlexEsisteGia/YtDesktop#4]
Appena effettuato l'accesso, l'app non rispondeva e mostrava solo la barra di ricerca. Successivamente, dopo averla riavviata, funzionava alla perfezione .

**Comment by Bildcraft1** [comment]
ti succede perchè l'app carica la pagina di Youtube music, ma non è un browser integrato, quindi il redirect dopo il login l'app non si refresha sulla pagina di YT Music dopo il login, proveremo ad integrare anche gli accounts di yt. 

Grazie per il report **Pollo2**

**Comment by Pollo2** [comment]
denghiu
